### ISSUE TITLE
Integrate with Weblate for easier translation contributions

### ISSUE THREAD

**Issue by scottAnselmo** [mmatyas/pegasus-frontend-translations#13]
It's noted via a TODO in the [documentation](https://pegasus-frontend.org/docs/dev/translate/), but I figured it would be best to make this a more formal issue. I suggest using Weblate for "some kind of online site for managing translations."

Weblate provides free hosting services for non-profit FOSS like this project, so you don't need to worry about creating your own Weblate server. Weblate also supports XML files and by Weblate hosting alongside other FOSS projects, Pegasus is more discoverable and might get more localizer eyes on it than it would otherwise. This is on top of other features like contributors being able to add a new language quite literally at the click of a button rather than fuss w/ manual file creation and edits.

**Comment by mmatyas** [comment]
Thanks, yes I was thinking about Weblate as a good choice a few years ago, and I see it made some nice improvements since then as well. Back then I had some issues with synching to and from the server and user management, but likely that got fixed by now. My other personal issue though is that it seems the free plan allows me to have only one hosted project -- and I happen to have over a hundred repositories on GitHub alone.

I'm okay with leaving this open though, will see if I can set things up with Weblate.

(Related: https://github.com/mmatyas/pegasus-frontend/issues/139)

**Comment by mmatyas** [comment]
There is now an experimental Transifex project here: https://explore.transifex.com/pegasus/pegasus-frontend/

Closing in favor of https://github.com/mmatyas/pegasus-frontend/issues/139
